[package]
name = "rust-play"
version = "0.1.0"
authors = ["LGN <792841450@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
