[workspace]

members = [
    "playground",
    "math",
    "bit_manipulation",
    "hash_table",
    "linked_list",
    "dynamic_programming",
    "sort",
    "binary_search",
    "two_pointers",
    "greedy",
    "string",
    "tree"
]
